# Generated by Django 4.2.13 on 2024-06-15 13:01

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Название площадки"),
                ),
                (
                    "pref_treatment",
                    models.CharField(
                        max_length=500, verbose_name="Преференциальный режим"
                    ),
                ),
                (
                    "pref_object",
                    models.CharField(
                        max_length=500,
                        verbose_name="Наименование объекта преференциального режима",
                    ),
                ),
                (
                    "pref_object_name",
                    models.CharField(
                        max_length=500,
                        verbose_name="Наименование объекта преференциального режима_наименование",
                    ),
                ),
                (
                    "support_infra_object",
                    models.CharField(
                        max_length=500, verbose_name="Объект инфраструктуры поддержки"
                    ),
                ),
                (
                    "support_name",
                    models.CharField(
                        max_length=500,
                        verbose_name="Наименование объекта инфраструктуры поддержки",
                    ),
                ),
                (
                    "support_name_detail",
                    models.CharField(
                        max_length=500,
                        verbose_name="Наименование объекта инфраструктуры поддержки_наименование",
                    ),
                ),
                ("region", models.CharField(max_length=500, verbose_name="Регион")),
                (
                    "municipal_entity",
                    models.CharField(
                        max_length=500, verbose_name="Муниципальное образование"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=500, verbose_name="Адрес объекта"),
                ),
                (
                    "nearest_city",
                    models.CharField(max_length=500, verbose_name="Ближайший город"),
                ),
                (
                    "site_format",
                    models.CharField(max_length=500, verbose_name="Формат площадки"),
                ),
                (
                    "site_type",
                    models.CharField(max_length=500, verbose_name="Тип площадки"),
                ),
                (
                    "ownership_form",
                    models.CharField(
                        max_length=500, verbose_name="Форма собственности объекта"
                    ),
                ),
                (
                    "transaction_form",
                    models.CharField(max_length=500, verbose_name="Форма сделки"),
                ),
                (
                    "cost_object",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Стоимость объекта, руб. (покупки или месячной аренды)",
                    ),
                ),
                (
                    "cost_per_year_ha",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Стоимость, руб./год за га",
                    ),
                ),
                (
                    "cost_per_year_sqm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Стоимость, руб./год за кв.м.",
                    ),
                ),
                (
                    "lease_term_min",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="min сроки аренды (если применимо), лет",
                    ),
                ),
                (
                    "lease_term_max",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="max сроки аренды (если применимо), лет",
                    ),
                ),
                (
                    "cost_determination_order",
                    models.CharField(
                        max_length=500, verbose_name="Порядок определения стоимости"
                    ),
                ),
                (
                    "hazard_class",
                    models.CharField(
                        max_length=500, verbose_name="Класс опасности объекта"
                    ),
                ),
                (
                    "building_characteristics",
                    models.TextField(
                        verbose_name="Характеристики расположенных объектов капитального строительства"
                    ),
                ),
                (
                    "free_land_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Свободная площадь ЗУ, га",
                    ),
                ),
                (
                    "cadastral_number_land",
                    models.CharField(
                        max_length=100, verbose_name="Кадастровый номер ЗУ"
                    ),
                ),
                (
                    "permitted_use_options",
                    models.TextField(
                        verbose_name="Варианты разрешенного использования"
                    ),
                ),
                ("land_surveying", models.BooleanField(verbose_name="Межевание ЗУ")),
                (
                    "land_category",
                    models.CharField(max_length=500, verbose_name="Категория земель"),
                ),
                (
                    "free_building_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Свободная площадь здания, сооружения, помещения, кв. м",
                    ),
                ),
                (
                    "cadastral_number_building",
                    models.CharField(
                        max_length=100,
                        verbose_name="Кадастровый номер здания, сооружения, помещения",
                    ),
                ),
                (
                    "building_technical_characteristics",
                    models.TextField(
                        verbose_name="Технические характеристики здания, сооружения, помещения"
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        max_length=500,
                        verbose_name="Наименование собственника / администратора объекта",
                    ),
                ),
                (
                    "owner_inn",
                    models.CharField(max_length=20, verbose_name="ИНН собственника"),
                ),
                ("website", models.URLField(verbose_name="Сайт")),
                ("note", models.TextField(verbose_name="Примечание")),
                (
                    "water_supply_available",
                    models.BooleanField(verbose_name="Водоснабжение Наличие (Да/Нет)"),
                ),
                (
                    "water_supply_rate_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Водоснабжение Тариф на потребление, руб./куб. м",
                    ),
                ),
                (
                    "water_supply_rate_transport",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Водоснабжение Тариф на транспортировку, руб./куб. м",
                    ),
                ),
                (
                    "water_supply_objects_max_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты водоснабжения Максимально допустимая мощность, куб. м/ч",
                    ),
                ),
                (
                    "water_supply_objects_free_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты водоснабжения Свободная мощность, куб.м/ч",
                    ),
                ),
                (
                    "water_supply_other_characteristics",
                    models.TextField(
                        verbose_name="Объекты водоснабжения Иные характеристики"
                    ),
                ),
                (
                    "water_network_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сети водоснабжения Пропускная способность, куб. м/ч",
                    ),
                ),
                (
                    "sewage_available",
                    models.BooleanField(verbose_name="Водоотведение Наличие (Да/Нет)"),
                ),
                (
                    "sewage_rate_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Водоотведение Тариф на потребление, руб./куб. м",
                    ),
                ),
                (
                    "sewage_rate_transport",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Водоотведение Тариф на транспортировку, руб./куб. м",
                    ),
                ),
                (
                    "sewage_objects_max_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты водоотведения Максимально допустимая мощность, куб. м/ч",
                    ),
                ),
                (
                    "sewage_objects_free_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты водоотведения Свободная мощность, куб. м/ч",
                    ),
                ),
                (
                    "sewage_other_characteristics",
                    models.TextField(
                        verbose_name="Объекты водоотведения Иные характеристики"
                    ),
                ),
                (
                    "sewage_network_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сети водоотведения Пропускная способность, куб. м/ч",
                    ),
                ),
                (
                    "gas_supply_available",
                    models.BooleanField(verbose_name="Газоснабжение Наличие (Да/Нет)"),
                ),
                (
                    "gas_supply_rate_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Газоснабжение Тариф на потребление, руб./куб. м",
                    ),
                ),
                (
                    "gas_supply_rate_transport",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Газоснабжение Тариф на транспортировку, руб./куб. м",
                    ),
                ),
                (
                    "gas_supply_objects_max_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты газоснабжения Максимально допустимая мощность, куб. м/ч",
                    ),
                ),
                (
                    "gas_supply_objects_free_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты газоснабжения Свободная мощность, куб. м/ч",
                    ),
                ),
                (
                    "gas_supply_other_characteristics",
                    models.TextField(
                        verbose_name="Объекты газоснабжения Иные характеристики"
                    ),
                ),
                (
                    "gas_network_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сети газоснабжения Пропускная способность, куб. м/ч",
                    ),
                ),
                (
                    "electricity_supply_available",
                    models.BooleanField(
                        verbose_name="Электроснабжение Наличие (Да/Нет)"
                    ),
                ),
                (
                    "electricity_rate_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Электроснабжение Тариф на потребление, руб./МВтч",
                    ),
                ),
                (
                    "electricity_rate_transport",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Электроснабжение Тариф на транспортировку, руб./МВтч",
                    ),
                ),
                (
                    "electricity_objects_max_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты электроснабжения Максимально допустимая мощность, МВт/ч",
                    ),
                ),
                (
                    "electricity_objects_free_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты электроснабжения Свободная мощность, МВт/ч",
                    ),
                ),
                (
                    "electricity_other_characteristics",
                    models.TextField(
                        verbose_name="Объекты электроснабжения Иные характеристики"
                    ),
                ),
                (
                    "electricity_network_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сети электроснабжения Пропускная способность, МВт/ч",
                    ),
                ),
                (
                    "heating_available",
                    models.BooleanField(verbose_name="Теплоснабжение Наличие (Да/Нет)"),
                ),
                (
                    "heating_rate_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Теплоснабжение Тариф на потребление, руб./Гкалч",
                    ),
                ),
                (
                    "heating_rate_transport",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Теплоснабжение Тариф на транспортировку, руб./Гкалч",
                    ),
                ),
                (
                    "heating_objects_max_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты теплоснабжения Максимально допустимая мощность, Гкал/ч",
                    ),
                ),
                (
                    "heating_objects_free_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Объекты теплоснабжения Свободная мощность, Гкал/ч",
                    ),
                ),
                (
                    "heating_other_characteristics",
                    models.TextField(
                        verbose_name="Объекты теплоснабжения Иные характеристики"
                    ),
                ),
                (
                    "heating_network_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сети теплоснабжения Пропускная способность, Гкал/ч",
                    ),
                ),
                (
                    "waste_disposal_available",
                    models.BooleanField(verbose_name="Вывоз ТКО Наличие (Да/Нет)"),
                ),
                (
                    "waste_disposal_rate_ton",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Вывоз ТКО Тариф, руб./тонна",
                    ),
                ),
                (
                    "waste_disposal_rate_cubic_meter",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Вывоз ТКО Тариф, руб./куб. м",
                    ),
                ),
                (
                    "access_roads_available",
                    models.BooleanField(
                        verbose_name="Наличие подъездных путей (Да/Нет)"
                    ),
                ),
                (
                    "railways_available",
                    models.BooleanField(verbose_name="Наличие ж/д (Да/Нет)"),
                ),
                (
                    "truck_parking_available",
                    models.BooleanField(
                        verbose_name="Наличие парковки грузового транспорта"
                    ),
                ),
                (
                    "other_characteristics",
                    models.TextField(verbose_name="Иные характеристики"),
                ),
                (
                    "application_procedure",
                    models.TextField(verbose_name="Описание процедуры подачи заявки"),
                ),
                (
                    "required_documents",
                    models.TextField(
                        verbose_name="Перечень документов, необходимых для подачи заявки"
                    ),
                ),
                (
                    "application_form_link",
                    models.URLField(verbose_name="Ссылка на форму подачи заявки"),
                ),
                (
                    "possible_activities",
                    models.TextField(
                        verbose_name="Перечень видов экономической деятельности, возможных к реализации на площадке"
                    ),
                ),
                (
                    "urban_planning_characteristics",
                    models.TextField(
                        verbose_name="Градостроительные характеристики и ограничения"
                    ),
                ),
                (
                    "territorial_planning_documents",
                    models.TextField(
                        verbose_name="Документы территориального планирования"
                    ),
                ),
                ("other_information", models.TextField(verbose_name="Иные сведения")),
                (
                    "object_photos",
                    models.ImageField(
                        upload_to="building_photos", verbose_name="Фотографии объекта"
                    ),
                ),
                ("maip_availability", models.BooleanField(verbose_name="Наличие МАИП")),
                (
                    "benefit_description",
                    models.TextField(verbose_name="Описание льготы"),
                ),
                (
                    "coordinates_lat",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Координаты: широта",
                    ),
                ),
                (
                    "coordinates_lon",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Координаты: долгота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект недвижимости",
                "verbose_name_plural": "Объекты недвижимости",
            },
        ),
        migrations.CreateModel(
            name="Technopark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Категория объекта"
                    ),
                ),
                (
                    "oez",
                    models.CharField(
                        max_length=500,
                        null=True,
                        verbose_name="Объект особого назначения",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=500,
                        null=True,
                        verbose_name='ОЭЗ "Технополис "Москва" - площадка "Печатники"',
                    ),
                ),
                (
                    "region",
                    models.CharField(max_length=500, null=True, verbose_name="Регион"),
                ),
                (
                    "region_object",
                    models.CharField(
                        max_length=500,
                        null=True,
                        verbose_name="Муниципальное образование",
                    ),
                ),
                (
                    "nearest_region",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Ближайший регион"
                    ),
                ),
                (
                    "num_residents",
                    models.IntegerField(
                        null=True, verbose_name="Количество резидентов"
                    ),
                ),
                (
                    "object_photos",
                    models.TextField(null=True, verbose_name="Фотографии объекта"),
                ),
                ("documents", models.TextField(null=True, verbose_name="Документы")),
                (
                    "year_of_object_forming",
                    models.IntegerField(
                        null=True, verbose_name="Год формирования объекта"
                    ),
                ),
                (
                    "year_of_object_destroy",
                    models.IntegerField(
                        null=True, verbose_name="Срок действия объекта, лет"
                    ),
                ),
                (
                    "total_square",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Общая площадь, кв. м",
                    ),
                ),
                (
                    "minimal_cost_of_buy",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальная стоимость аренды, руб./кв.м/год",
                    ),
                ),
                (
                    "ability_to_buy",
                    models.BooleanField(
                        null=True,
                        verbose_name="Возможность выкупа помещения / участка (да / нет)",
                    ),
                ),
                (
                    "list_of_activities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        null=True,
                        size=None,
                        verbose_name="Перечень видов деятельности",
                    ),
                ),
                (
                    "restrictions",
                    models.TextField(
                        null=True, verbose_name="Ограничения по видам деятельности"
                    ),
                ),
                (
                    "infrastructure",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        null=True,
                        size=None,
                        verbose_name="Инфраструктура и сервисы",
                    ),
                ),
                (
                    "additional_infra",
                    models.TextField(
                        null=True,
                        verbose_name="Дополнительные услуги управляющей компании",
                    ),
                ),
                (
                    "name_of_administration_object",
                    models.CharField(
                        max_length=500,
                        null=True,
                        verbose_name="Название администратора объекта",
                    ),
                ),
                (
                    "address_administration_object",
                    models.CharField(
                        max_length=500,
                        null=True,
                        verbose_name="Адрес администратора объекта",
                    ),
                ),
                ("link", models.URLField(null=True, verbose_name="Ссылка на сайт")),
                (
                    "work_time",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Время работы"
                    ),
                ),
                (
                    "tax_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Налог на прибыль",
                    ),
                ),
                (
                    "tax_estate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Налог на имущество",
                    ),
                ),
                (
                    "tax_ground",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Земельный налог",
                    ),
                ),
                (
                    "tax_transport",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Транспортный налог",
                    ),
                ),
                (
                    "insurance_premiums",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Страховые взносы",
                    ),
                ),
                (
                    "another_benefits",
                    models.TextField(null=True, verbose_name="Прочие льготы"),
                ),
                (
                    "free_custom_zone",
                    models.BooleanField(
                        null=True,
                        verbose_name="Наличие режима свободной таможенной зоны (да/нет), условия",
                    ),
                ),
                (
                    "how_to_become_resident",
                    models.TextField(verbose_name="Как стать резидентом"),
                ),
                (
                    "minimal_investment_volume",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный объём инвестиций, млн руб",
                    ),
                ),
                (
                    "coords_lat",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Координаты: широта",
                    ),
                ),
                (
                    "coords_lon",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Координаты: долгота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Технопарк",
                "verbose_name_plural": "Технопарки",
            },
        ),
        migrations.CreateModel(
            name="TechnoparkSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Регион"
                    ),
                ),
                (
                    "min_num_residents",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Минимальное количество резидентов",
                    ),
                ),
                (
                    "max_num_residents",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальное количество резидентов",
                    ),
                ),
                (
                    "min_year_of_object_forming",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Минимальный год формирования объекта",
                    ),
                ),
                (
                    "max_year_of_object_forming",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальный год формирования объекта",
                    ),
                ),
                (
                    "min_total_square",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Минимальная общая площадь, кв. м",
                    ),
                ),
                (
                    "max_total_square",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальная общая площадь, кв. м",
                    ),
                ),
                (
                    "min_minimal_cost_of_buy",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Минимальная стоимость аренды, руб./кв.м/год",
                    ),
                ),
                (
                    "max_minimal_cost_of_buy",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальная стоимость аренды, руб./кв.м/год",
                    ),
                ),
                (
                    "list_of_activities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        null=True,
                        size=None,
                        verbose_name="Перечень видов деятельности",
                    ),
                ),
                (
                    "infrastructure",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        null=True,
                        size=None,
                        verbose_name="Инфраструктура и сервисы",
                    ),
                ),
                (
                    "min_tax_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Минимальный налог на прибыль",
                    ),
                ),
                (
                    "max_tax_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Максимальный налог на прибыль",
                    ),
                ),
                (
                    "min_tax_estate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Минимальный налог на имущество",
                    ),
                ),
                (
                    "max_tax_estate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Максимальный налог на имущество",
                    ),
                ),
                (
                    "min_tax_ground",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Минимальный земельный налог",
                    ),
                ),
                (
                    "max_tax_ground",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Максимальный земельный налог",
                    ),
                ),
                (
                    "min_tax_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Минимальный транспортный налог",
                    ),
                ),
                (
                    "max_tax_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Максимальный транспортный налог",
                    ),
                ),
                (
                    "min_insurance_premiums",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Минимальные страховые взносы",
                    ),
                ),
                (
                    "max_insurance_premiums",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Максимальные страховые взносы",
                    ),
                ),
                (
                    "free_custom_zone",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Наличие режима свободной таможенной зоны",
                    ),
                ),
                (
                    "min_minimal_investment_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный объем инвестиций, млн руб",
                    ),
                ),
                (
                    "max_minimal_investment_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный объем инвестиций, млн руб",
                    ),
                ),
                (
                    "additional_preferences",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Дополнительные предпочтения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на технопарк",
                "verbose_name_plural": "Заявки на технопарк",
            },
        ),
    ]
