# Generated by Django 4.2.13 on 2024-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_technoparksubmission_user_alter_technopark_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="technoparksubmission",
            name="name",
            field=models.CharField(
                default="Новый чат", max_length=500, verbose_name="Имя чата"
            ),
        ),
    ]
