# Generated by Django 4.2.13 on 2024-06-15 15:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_technoparksubmission_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingmodel",
            name="access_roads_available",
            field=models.BooleanField(
                null=True, verbose_name="Наличие подъездных путей (Да/Нет)"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="address",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Адрес объекта"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="application_form_link",
            field=models.URLField(
                null=True, verbose_name="Ссылка на форму подачи заявки"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="application_procedure",
            field=models.TextField(
                null=True, verbose_name="Описание процедуры подачи заявки"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="benefit_description",
            field=models.TextField(null=True, verbose_name="Описание льготы"),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="building_characteristics",
            field=models.TextField(
                null=True,
                verbose_name="Характеристики расположенных объектов капитального строительства",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="building_technical_characteristics",
            field=models.TextField(
                null=True,
                verbose_name="Технические характеристики здания, сооружения, помещения",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="cadastral_number_building",
            field=models.CharField(
                max_length=100,
                null=True,
                verbose_name="Кадастровый номер здания, сооружения, помещения",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="cadastral_number_land",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Кадастровый номер ЗУ"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="cost_determination_order",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Порядок определения стоимости"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="cost_object",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Стоимость объекта, руб. (покупки или месячной аренды)",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="cost_per_year_ha",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Стоимость, руб./год за га",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="cost_per_year_sqm",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Стоимость, руб./год за кв.м.",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="electricity_network_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сети электроснабжения Пропускная способность, МВт/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="electricity_objects_free_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты электроснабжения Свободная мощность, МВт/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="electricity_objects_max_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты электроснабжения Максимально допустимая мощность, МВт/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="electricity_other_characteristics",
            field=models.TextField(
                null=True, verbose_name="Объекты электроснабжения Иные характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="electricity_rate_consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Электроснабжение Тариф на потребление, руб./МВтч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="electricity_rate_transport",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Электроснабжение Тариф на транспортировку, руб./МВтч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="electricity_supply_available",
            field=models.BooleanField(
                null=True, verbose_name="Электроснабжение Наличие (Да/Нет)"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="free_building_area",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Свободная площадь здания, сооружения, помещения, кв. м",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="free_land_area",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Свободная площадь ЗУ, га",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="gas_network_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сети газоснабжения Пропускная способность, куб. м/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="gas_supply_available",
            field=models.BooleanField(
                null=True, verbose_name="Газоснабжение Наличие (Да/Нет)"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="gas_supply_objects_free_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты газоснабжения Свободная мощность, куб. м/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="gas_supply_objects_max_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты газоснабжения Максимально допустимая мощность, куб. м/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="gas_supply_other_characteristics",
            field=models.TextField(
                null=True, verbose_name="Объекты газоснабжения Иные характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="gas_supply_rate_consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Газоснабжение Тариф на потребление, руб./куб. м",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="gas_supply_rate_transport",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Газоснабжение Тариф на транспортировку, руб./куб. м",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="hazard_class",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Класс опасности объекта"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="heating_available",
            field=models.BooleanField(
                null=True, verbose_name="Теплоснабжение Наличие (Да/Нет)"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="heating_network_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сети теплоснабжения Пропускная способность, Гкал/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="heating_objects_free_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты теплоснабжения Свободная мощность, Гкал/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="heating_objects_max_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты теплоснабжения Максимально допустимая мощность, Гкал/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="heating_other_characteristics",
            field=models.TextField(
                null=True, verbose_name="Объекты теплоснабжения Иные характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="heating_rate_consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Теплоснабжение Тариф на потребление, руб./Гкалч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="heating_rate_transport",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Теплоснабжение Тариф на транспортировку, руб./Гкалч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="land_category",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Категория земель"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="land_surveying",
            field=models.BooleanField(null=True, verbose_name="Межевание ЗУ"),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="maip_availability",
            field=models.BooleanField(null=True, verbose_name="Наличие МАИП"),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="municipal_entity",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Муниципальное образование"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="name",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Название площадки"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="nearest_city",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Ближайший город"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="note",
            field=models.TextField(null=True, verbose_name="Примечание"),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="object_photos",
            field=models.ImageField(
                null=True,
                upload_to="building_photos",
                verbose_name="Фотографии объекта",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="other_characteristics",
            field=models.TextField(null=True, verbose_name="Иные характеристики"),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="other_information",
            field=models.TextField(null=True, verbose_name="Иные сведения"),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="owner_inn",
            field=models.CharField(
                max_length=20, null=True, verbose_name="ИНН собственника"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="owner_name",
            field=models.CharField(
                max_length=500,
                null=True,
                verbose_name="Наименование собственника / администратора объекта",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="ownership_form",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Форма собственности объекта"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="permitted_use_options",
            field=models.TextField(
                null=True, verbose_name="Варианты разрешенного использования"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="possible_activities",
            field=models.TextField(
                null=True,
                verbose_name="Перечень видов экономической деятельности, возможных к реализации на площадке",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="pref_object",
            field=models.CharField(
                max_length=500,
                null=True,
                verbose_name="Наименование объекта преференциального режима",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="pref_object_name",
            field=models.CharField(
                max_length=500,
                null=True,
                verbose_name="Наименование объекта преференциального режима_наименование",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="pref_treatment",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Преференциальный режим"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="railways_available",
            field=models.BooleanField(null=True, verbose_name="Наличие ж/д (Да/Нет)"),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="region",
            field=models.CharField(max_length=500, null=True, verbose_name="Регион"),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="required_documents",
            field=models.TextField(
                null=True,
                verbose_name="Перечень документов, необходимых для подачи заявки",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="sewage_available",
            field=models.BooleanField(
                null=True, verbose_name="Водоотведение Наличие (Да/Нет)"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="sewage_network_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сети водоотведения Пропускная способность, куб. м/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="sewage_objects_free_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты водоотведения Свободная мощность, куб. м/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="sewage_objects_max_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты водоотведения Максимально допустимая мощность, куб. м/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="sewage_other_characteristics",
            field=models.TextField(
                null=True, verbose_name="Объекты водоотведения Иные характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="sewage_rate_consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоотведение Тариф на потребление, руб./куб. м",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="sewage_rate_transport",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоотведение Тариф на транспортировку, руб./куб. м",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="site_format",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Формат площадки"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="site_type",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Тип площадки"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="support_infra_object",
            field=models.CharField(
                max_length=500,
                null=True,
                verbose_name="Объект инфраструктуры поддержки",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="support_name",
            field=models.CharField(
                max_length=500,
                null=True,
                verbose_name="Наименование объекта инфраструктуры поддержки",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="territorial_planning_documents",
            field=models.TextField(
                null=True, verbose_name="Документы территориального планирования"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="transaction_form",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Форма сделки"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="truck_parking_available",
            field=models.BooleanField(
                null=True, verbose_name="Наличие парковки грузового транспорта"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="urban_planning_characteristics",
            field=models.TextField(
                null=True, verbose_name="Градостроительные характеристики и ограничения"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="waste_disposal_available",
            field=models.BooleanField(
                null=True, verbose_name="Вывоз ТКО Наличие (Да/Нет)"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="waste_disposal_rate_cubic_meter",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Вывоз ТКО Тариф, руб./куб. м",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="waste_disposal_rate_ton",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Вывоз ТКО Тариф, руб./тонна",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="water_network_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Сети водоснабжения Пропускная способность, куб. м/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="water_supply_available",
            field=models.BooleanField(
                null=True, verbose_name="Водоснабжение Наличие (Да/Нет)"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="water_supply_objects_free_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты водоснабжения Свободная мощность, куб.м/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="water_supply_objects_max_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объекты водоснабжения Максимально допустимая мощность, куб. м/ч",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="water_supply_other_characteristics",
            field=models.TextField(
                null=True, verbose_name="Объекты водоснабжения Иные характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="water_supply_rate_consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоснабжение Тариф на потребление, руб./куб. м",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="water_supply_rate_transport",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоснабжение Тариф на транспортировку, руб./куб. м",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="website",
            field=models.URLField(null=True, verbose_name="Сайт"),
        ),
        migrations.CreateModel(
            name="BuildingSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Новый чат", max_length=500, verbose_name="Имя чата"
                    ),
                ),
                (
                    "pref_treatment",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Преференциальный режим"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Регион"
                    ),
                ),
                (
                    "site_format",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        null=True,
                        size=None,
                        verbose_name="Формат площадки",
                    ),
                ),
                (
                    "site_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        null=True,
                        size=None,
                        verbose_name="Тип площадки",
                    ),
                ),
                (
                    "transaction_form",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        null=True,
                        size=None,
                        verbose_name="Форма сделки",
                    ),
                ),
                (
                    "min_cost_object",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальная стоимость объекта, руб.",
                    ),
                ),
                (
                    "max_cost_object",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальная стоимость объекта, руб.",
                    ),
                ),
                (
                    "water_supply_available",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Водоснабжение Наличие"
                    ),
                ),
                (
                    "min_water_supply_rate_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный тариф на потребление водоснабжения, руб./куб. м",
                    ),
                ),
                (
                    "max_water_supply_rate_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный тариф на потребление водоснабжения, руб./куб. м",
                    ),
                ),
                (
                    "min_water_supply_rate_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный тариф на транспортировку водоснабжения, руб./куб. м",
                    ),
                ),
                (
                    "max_water_supply_rate_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный тариф на транспортировку водоснабжения, руб./куб. м",
                    ),
                ),
                (
                    "min_water_supply_objects_max_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальная максимально допустимая мощность объектов водоснабжения, куб. м/ч",
                    ),
                ),
                (
                    "max_water_supply_objects_max_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальная максимально допустимая мощность объектов водоснабжения, куб. м/ч",
                    ),
                ),
                (
                    "gas_supply_available",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Газоснабжение Наличие"
                    ),
                ),
                (
                    "min_gas_supply_rate_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный тариф на потребление газоснабжения, руб./куб. м",
                    ),
                ),
                (
                    "max_gas_supply_rate_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный тариф на потребление газоснабжения, руб./куб. м",
                    ),
                ),
                (
                    "min_gas_supply_rate_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный тариф на транспортировку газоснабжения, руб./куб. м",
                    ),
                ),
                (
                    "max_gas_supply_rate_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный тариф на транспортировку газоснабжения, руб./куб. м",
                    ),
                ),
                (
                    "electricity_supply_available",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Электроснабжение Наличие"
                    ),
                ),
                (
                    "min_electricity_rate_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный тариф на потребление электроснабжения, руб./МВтч",
                    ),
                ),
                (
                    "max_electricity_rate_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный тариф на потребление электроснабжения, руб./МВтч",
                    ),
                ),
                (
                    "min_electricity_rate_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный тариф на транспортировку электроснабжения, руб./МВтч",
                    ),
                ),
                (
                    "max_electricity_rate_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный тариф на транспортировку электроснабжения, руб./МВтч",
                    ),
                ),
                (
                    "heating_available",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Теплоснабжение Наличие"
                    ),
                ),
                (
                    "min_heating_rate_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный тариф на потребление теплоснабжения, руб./Гкалч",
                    ),
                ),
                (
                    "max_heating_rate_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный тариф на потребление теплоснабжения, руб./Гкалч",
                    ),
                ),
                (
                    "min_heating_rate_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный тариф на транспортировку теплоснабжения, руб./Гкалч",
                    ),
                ),
                (
                    "max_heating_rate_transport",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный тариф на транспортировку теплоснабжения, руб./Гкалч",
                    ),
                ),
                (
                    "waste_disposal_available",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Вывоз ТКО Наличие"
                    ),
                ),
                (
                    "min_waste_disposal_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Минимальный тариф на вывоз ТКО",
                    ),
                ),
                (
                    "max_waste_disposal_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальный тариф на вывоз ТКО",
                    ),
                ),
                (
                    "access_roads_available",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Наличие подъездных путей"
                    ),
                ),
                (
                    "railways_available",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Наличие ж/д"
                    ),
                ),
                (
                    "truck_parking_available",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Наличие парковки грузового транспорта",
                    ),
                ),
                (
                    "additional_comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Дополнительные комментарии"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на подбор здания",
                "verbose_name_plural": "Заявки на подбор здания",
            },
        ),
    ]
