# Generated by Django 4.2.13 on 2024-06-15 16:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_buildingmodel_access_roads_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingmodel",
            name="cadastral_number_building",
            field=models.CharField(
                max_length=500,
                null=True,
                verbose_name="Кадастровый номер здания, сооружения, помещения",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="cadastral_number_land",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Кадастровый номер ЗУ"
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="site_format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                null=True,
                size=None,
                verbose_name="Формат площадки",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="site_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                null=True,
                size=None,
                verbose_name="Тип площадки",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="transaction_form",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                null=True,
                size=None,
                verbose_name="Форма сделки",
            ),
        ),
    ]
