# Generated by Django 4.2.13 on 2024-06-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_buildingmodel_cadastral_number_building_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingmodel",
            name="website",
            field=models.URLField(max_length=500, null=True, verbose_name="Сайт"),
        ),
    ]
