# Generated by Django 4.2.13 on 2024-06-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_buildingmodel_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildingmodel",
            name="object_photos",
        ),
    ]
