# Generated by Django 4.2.13 on 2024-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_remove_buildingmodel_object_photos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingmodel",
            name="support_name_detail",
            field=models.CharField(
                max_length=500,
                null=True,
                verbose_name="Наименование объекта инфраструктуры поддержки_наименование",
            ),
        ),
    ]
