# Generated by Django 4.2.13 on 2024-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_buildingmodel_support_name_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingsubmission",
            name="state",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="technoparksubmission",
            name="state",
            field=models.IntegerField(default=0),
        ),
    ]
