# Generated by Django 4.2.13 on 2024-06-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingsubmission",
            name="ml_data",
            field=models.JSONField(null=True, verbose_name="Данные от ML"),
        ),
        migrations.AddField(
            model_name="technoparksubmission",
            name="ml_data",
            field=models.JSONField(null=True, verbose_name="Данные от ML"),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_user",
                    models.BooleanField(verbose_name="Отправитель - пользователь"),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chat",
                        verbose_name="Чат",
                    ),
                ),
            ],
        ),
    ]
