# Generated by Django 4.2.13 on 2024-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_buildingsubmission_ml_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildingmodel",
            name="electricity_rate_consumption",
        ),
        migrations.RemoveField(
            model_name="buildingmodel",
            name="gas_supply_rate_consumption",
        ),
        migrations.RemoveField(
            model_name="buildingmodel",
            name="water_supply_rate_consumption",
        ),
        migrations.RemoveField(
            model_name="buildingmodel",
            name="water_supply_rate_transport",
        ),
        migrations.RemoveField(
            model_name="buildingsubmission",
            name="max_gas_supply_rate_consumption",
        ),
        migrations.RemoveField(
            model_name="buildingsubmission",
            name="max_water_supply_rate_consumption",
        ),
        migrations.RemoveField(
            model_name="buildingsubmission",
            name="min_gas_supply_rate_consumption",
        ),
        migrations.RemoveField(
            model_name="buildingsubmission",
            name="min_water_supply_rate_consumption",
        ),
        migrations.AddField(
            model_name="buildingmodel",
            name="electricity_rate_consumption_max",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Электроснабжение Тариф на потребление, максимальный, руб./КВт*ч",
            ),
        ),
        migrations.AddField(
            model_name="buildingmodel",
            name="electricity_rate_consumption_min",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Электроснабжение Тариф на потребление, минимальный, руб./КВт*ч",
            ),
        ),
        migrations.AddField(
            model_name="buildingmodel",
            name="gas_supply_rate_consumption_max",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Газоснабжение Тариф на потребление, максимальный, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingmodel",
            name="gas_supply_rate_consumption_min",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Газоснабжение Тариф на потребление, минимальный, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingmodel",
            name="water_supply_rate_consumption_max",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоснабжение Тариф на потребление, максимальный, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingmodel",
            name="water_supply_rate_consumption_min",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоснабжение Тариф на потребление, минимальный, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingmodel",
            name="water_supply_rate_transport_max",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоснабжение Тариф на транспортировку, максимальный, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingmodel",
            name="water_supply_rate_transport_min",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоснабжение Тариф на транспортировку, минимальный, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingsubmission",
            name="gas_supply_rate_consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Газоснабжение Тариф на потребление, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingsubmission",
            name="gas_supply_rate_consumption_max",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Газоснабжение Тариф на потребление, максимальный, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingsubmission",
            name="gas_supply_rate_consumption_min",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Газоснабжение Тариф на потребление, минимальный, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingsubmission",
            name="water_supply_rate_consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоснабжение Тариф на потребление, руб./куб. м",
            ),
        ),
        migrations.AlterField(
            model_name="buildingmodel",
            name="heating_rate_transport",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Теплоснабжение Тариф на транспортировку, руб./Гкал*ч",
            ),
        ),
    ]
