# Generated by Django 4.2.13 on 2024-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_remove_buildingmodel_electricity_rate_consumption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="chat_files", verbose_name="Файл"
            ),
        ),
    ]
