# Generated by Django 4.2.13 on 2024-06-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_buildingsubmission_pref_treatment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildingsubmission",
            name="water_supply_rate_consumption",
        ),
        migrations.AddField(
            model_name="buildingsubmission",
            name="max_water_supply_rate_consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоснабжение Тариф на потребление, максимальный, руб./куб. м",
            ),
        ),
        migrations.AddField(
            model_name="buildingsubmission",
            name="min_water_supply_rate_consumption",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Водоснабжение Тариф на потребление, минимальный, руб./куб. м",
            ),
        ),
    ]
